export enum NotificationType {
  TOURNAMENT_ANNOUNCEMENT = 'tournament_announcement',
  SCORE_UPDATE = 'score_update',
  BRACKET_UPDATE = 'bracket_update',
  REGISTRATION_CONFIRMATION = 'registration_confirmation',
  REGISTRATION_STATUS_CHANGE = 'registration_status_change',
  PAYMENT_CONFIRMATION = 'payment_confirmation',
  SYSTEM_ALERT = 'system_alert',
  // Aligned with backend NotificationType (subset used by UI)
  STANDINGS_UPDATE = 'standings_update',
  UPCOMING_EVENT = 'upcoming_event',
  ROUND_RESULT = 'round_result',
  SIDEACTION_UPDATE = 'sideaction_update',
  TOURNAMENT_REGISTRATION = 'tournament_registration',
  SYSTEM_MESSAGE = 'system_message',
  EVENT_SIGNUP_PENDING = 'event_signup_pending',
  TEAM_SIGNUP_PENDING = 'team_signup_pending',
  EVENT_SIGNUP_ACCEPTED = 'event_signup_accepted',
  EVENT_SIGNUP_REJECTED = 'event_signup_rejected',
  TOURNAMENT_PARTICIPANT_STATUS = 'tournament_participant_status',
}