/** Stable `data-guide-id` values for spotlight / nav-skip / field-flash targets. */
export const GUIDE_IDS = {
  CREATE_TOURNAMENT: 'guide-create-tournament',
  CREATE_EVENT: 'guide-create-event',
  CREATE_TOURNAMENT_SUBMIT: 'guide-create-tournament-submit',
  CREATE_EVENT_SUBMIT: 'guide-create-event-submit',
  BOWLING_CENTERS_NAV: 'guide-bowling-centers',
  SUBSCRIPTION_NAV: 'guide-subscription',
  TAB_PARTICIPANTS: 'guide-tab-participants',
  TAB_SQUADS: 'guide-tab-squads',
  TAB_LANES: 'guide-tab-lanes',
  TAB_SCORING: 'guide-tab-scoring',
  TAB_FORMAT: 'guide-tab-format',
  TAB_SIDE_ACTIONS: 'guide-tab-side-actions',
  TAB_STANDINGS: 'guide-tab-standings',
  EVENT_REPORTS: 'guide-event-reports',
  ADD_PARTICIPANTS: 'guide-add-participants',
  LOCK_SQUAD: 'guide-lock-squad',
  LOCK_SA_ENTRIES: 'guide-lock-sa-entries',
  CREATE_SIDE_ACTION: 'guide-create-side-action',
  /** Required field targets for fill coaching / flash */
  TOURNAMENT_NAME: 'guide-field-tournament-name',
  TOURNAMENT_CENTER: 'guide-field-tournament-center',
  EVENT_NAME: 'guide-field-event-name',
  EVENT_FORMAT: 'guide-field-event-format',
  EVENT_REENTRY: 'guide-field-event-reentry',
  EVENT_START: 'guide-field-event-start',
  EVENT_END: 'guide-field-event-end',
  EVENT_SUBMIT: 'guide-create-event-submit',
  PARTICIPANT_AVERAGE: 'guide-participant-average',
  PARTICIPANT_ROW_PREFIX: 'guide-participant-row-',
  /** Event structure wizard / format builder */
  FORMAT_WIZARD: 'guide-format-wizard',
  FORMAT_ADD_STAGE: 'guide-format-add-stage',
  FORMAT_ADD_RELATIONSHIP: 'guide-format-add-relationship',
  FORMAT_ADD_FINAL: 'guide-format-add-final',
  FORMAT_SAVE: 'guide-format-save',
  FORMAT_APPLY_TO_EVENT: 'guide-format-apply-to-event',
  FORMAT_NAME: 'guide-format-name',
  FORMAT_DESCRIPTION: 'guide-format-description',
  FORMAT_ROUND_GAMES: 'guide-format-round-games',
  FORMAT_ROUND_METHOD: 'guide-format-round-method',
  FORMAT_ROUND_SCORE_TYPE: 'guide-format-round-score-type',
  FORMAT_REL_SOURCE: 'guide-format-rel-source',
  FORMAT_REL_TARGET: 'guide-format-rel-target',
  FORMAT_REL_FILTER: 'guide-format-rel-filter',
  FORMAT_REL_COUNT: 'guide-format-rel-count',
  FORMAT_REL_PERCENT: 'guide-format-rel-percent',
  FORMAT_REL_EXEC_ORDER: 'guide-format-rel-execution-order',
  FORMAT_FINAL_NAME: 'guide-format-final-name',
  FORMAT_FINAL_PLACEMENT: 'guide-format-final-placement',
} as const;

export type GuideId = (typeof GUIDE_IDS)[keyof typeof GUIDE_IDS];

/** CSS class toggled for the 3× slow field blink. */
export const GUIDE_FIELD_FLASH_CLASS = 'guide-field-flash';
